# Generated by Django 5.2.4 on 2025-07-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_tale_suggestion_delete_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='tale',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
