# Generated by Django 5.2.4 on 2025-07-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Showcase',
        ),
    ]
